### ISSUE TITLE
updating the geojson

### ISSUE THREAD

**Issue by iannesbitt** [nofurtherinformation/covid-country#1]
How would one go about updating the data source? Where does the underlying geojson come from, and can a call to extract that data be replicated somehow?

**Comment by nofurtherinformation** [comment]
For the short term, you could grab the off-the-shelf US Covid Atlas geojsons located [here](https://github.com/GeoDaCenter/covid/tree/master/docs) (GPL License). You can also sign up for API access for the US Covid Atlas on [this page](https://theuscovidatlas.org/api.html) and join the return based on GEOID/FIPS codes.

**Comment by iannesbitt** [comment]
Much appreciated, thank you.
